config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :giftees do
    resources :wishlists
  end

  resources :users
  resources :sessions, :only => [:new, :create]

  get '/sessions/new' => 'sessions#new', as: :login
  delete '/logout' => 'sessions#destroy', as: :logout
  get '/users/new' => 'users#new', as: :signup

end

app/models/giftee.rb
class Giftee < ActiveRecord::Base
  has_many :wishlists
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :giftees


  validates :name, presence: true
  validates :name, uniqueness: true

  validates :email, presence: true
  validates :email, uniqueness: true

  validates_confirmation_of :password, :message => "Passwords should match"
  has_secure_password
  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :giftee
  validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user 

  def current_user
    if session[:user_id] && !!User.exists?(session[:user_id])
      @current_user ||= User.find(session[:user_id])
    end
  end

  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to view this section"
      redirect_to new_session_path
    end
  end
  
end

app/controllers/giftees_controller.rb
class GifteesController < ApplicationController
  before_action :only_owner, only: [:edit, :update, :show, :destroy]
  before_action :require_login, only: [:index, :new, :create] 


  def index
    @giftees = @current_user.giftees
    @title = "My Giftees"
  end

  def show
    id = params[:id]
    @giftee = Giftee.find(id)
    @title = "#{@giftee.name}'s Info"
    @name = @giftee.name
  end

  def new
    @giftee = Giftee.new()
    @action = "create"
    @title = "Add a New Giftee"
  end

  def create
    giftee = Giftee.create(giftee_params[:giftee])
    giftee.user_id = session[:user_id]
    giftee.save
    redirect_to user_path(@current_user)
  end

  def edit
    id = params[:id]
    @giftee = Giftee.find(id)
    @action = "update"
    @title = "Edit a Giftee"
  end

  def update
    id = params[:id]
    Giftee.update(id, giftee_params[:giftee])
    redirect_to giftee_path(id)
  end

  def destroy
    id = params[:id]
    Giftee.destroy(id)
    redirect_to giftees_path
  end

  private

  def giftee_params
    params.permit(giftee:[:name, :age, :likes, :dislikes])
  end

  def only_owner
      if !@current_user || @current_user.id != Giftee.find(params[:id]).user_id
        flash[:error] = "You are not authorized to view that section"
        redirect_to root_path
      end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    data = params[:session_data]
    @user = User.find_by_email(data[:email])

    if !@user.nil?
      if @user.authenticate(data[:password])
        session[:user_id] = @user.id
        flash[:notice] = "Welcome, #{@user.name}!"
        redirect_to user_path(@user)
      else
        flash.now[:error] = "Your email was not found or password did not match. Please try again."
        render :new
      end
    else
      flash.now[:error] = "Your email was not found or password did not match. Please try again or sign up to create a new user."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil if session[:user_id]
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end

  private

  def session_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(strong_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome! You are now logged in."
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  private

  def strong_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :only_owner

  def index
    id = params[:giftee_id]
    @giftee = Giftee.find(id)
    @title = "#{@giftee.name}'s Wishlist"
    @wishlists = @giftee.wishlists
  end

  def show
    id = params[:giftee_id]
    @giftee = Giftee.find(id)
    @title = "Market Vendors"
    @wishlists = @giftee.wishlists
  end

  def new
    @wishlist = Wishlist.new(wishlist_params[:wishlist])
    @action = "create"
    @title = "Add Item"
  end

  def create
    @giftee_id = params[:giftee_id]
    new_params = wishlist_params[:wishlist]
    new_params[:giftee_id] = @giftee_id
    Wishlist.create(new_params)
    redirect_to giftee_wishlists_path
  end

  def edit
    wishlist_id = params[:id]
    @wishlist = Wishlist.find(wishlist_id)
    @action = "update"
    @title = "Edit an Item"
  end

  def update
    id = params[:id]
    Wishlist.update(id, wishlist_params[:wishlist])
    redirect_to giftee_wishlists_path
  end

  def destroy
    id = params[:id]
    Wishlist.destroy(id)
    redirect_to giftee_wishlists_path
  end

  private

  def wishlist_params
    params.permit(wishlist:[:item, :price, :bought])
  end

  def only_owner
      if !@current_user || @current_user.id != Giftee.find(params[:id]).user_id
        flash[:error] = "You are not authorized to view that section"
        redirect_to root_path
      end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/accounts/new.html.erb
<div class="new-account-form">

<%= bootstrap_form_for @account, class: "form-group", url:({action: "#{@action}"}) do |f| %>
<%= f.text_field :name%>
<%= f.text_field :user_login%>
<%= f.submit class: "submit", class: "btn btn-default" %>
<% end %>
</div>

app/views/giftees/_form.html.erb
<div class="giftee-form">
<h1><%= @title %></h1>

<%= bootstrap_form_for @giftee, class: "form-group", url:({action: @action}) do |f| %>
<%= f.text_field :name%>
<%= f.text_field :age%>
<%= f.text_field :likes%>
<%= f.text_field :dislikes%>
<%= f.submit class: "submit", class: "btn btn-default" %>
<% end %>

</div>

app/views/giftees/index.html.erb
<h1><%= @title %></h1>
<section class="giftee-list">
  <% @giftees.each do |giftee| %>
    <h4><%= link_to giftee.name, giftee_path(giftee.id), method: :get%></h4>
  <% end %>
</section>
<%= button_to "Add New Giftee", new_giftee_path, method: :get, class: "btn btn-default" %>

app/views/giftees/show.html.erb
<h1><%= @title %></h1>
<div class="table-master">
<table class='table table-hover'>
  <tr>
    <td class="table-headers">
      Name
    </td>
    <td>
      <%= @giftee.name %>
    </td>
  </tr>
  <tr>
    <td class="table-headers">
      Age
    </td>
    <td>
      <%= @giftee.age %>
    </td>
  </tr>
  <tr>
    <td class="table-headers">
      Likes
    </td>
    <td>
      <%= @giftee.likes %>
    </td>
  </tr>
  <tr>
    <td class="table-headers">
      Dislikes
    </td>
    <td>
      <%= @giftee.dislikes %>
    </td>
  </tr>
</table>
</div>

<%= link_to "View Wishlist", giftee_wishlists_path(@giftee.id), role: "button", class: "btn btn-default" %>
<%= button_to "Edit Profile", edit_giftee_path(@giftee), method: :get, class: "btn btn-default" %>
<%= button_to "Delete Profile", "/giftees/#{@giftee.id}", method: :delete, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giftees</title>
    <link href='https://fonts.googleapis.com/css?family=Mountains+of+Christmas:700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link href="/favicon.ico" rel="shortcut icon" type="image/png">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav><%= link_to "Giftees", root_path %> <span class="header-description">A Whimsical Wishlist Website</span></nav>
    </header>
    <% if !flash.empty? %>
      <div class="flash">
        <% flash.each do |key, value| %><%= value %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
    <nav>
     <%= link_to 'Home', root_path %>
    </nav>
  </body>
</html>

app/views/users/new.html.erb
<div class="col-sm-12">
  <h1 class="header-box">
    Sign Up
  </h1>
    <%= form_for @user do |f| %>
    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name,  class: "form-control" %><br>

    <%= f.label :email %>
    <%= f.text_field :email,  class: "form-control" %><br>

    <%= f.label :password %>
    <%= f.password_field :password,  class: "form-control" %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation,  class: "form-control" %><br>

    <%= f.submit class: 'btn btn-default' %><br>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>
<%= button_to 'My Giftees', giftees_path, method: :get, class: 'btn btn-default' %>
<%= button_to 'Add a Giftee', new_giftee_path, method: :get, class: 'btn btn-default' %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<br><br>
<% if @current_user %>
  <%= link_to "My Profile", user_path(@current_user) %><br>
  <%= link_to "Log Out", logout_path, method: :delete %>
<% else %>
  <%= link_to "Sign Up!", signup_path %><br>
  <%= link_to "Log In", login_path %>
<% end %>

app/views/wishlists/_form.html.erb
<div class="wishlist-form">
<h1><%= @title %></h1>

<%= bootstrap_form_for @wishlist, class: "form-group", url:({action: @action}) do |f| %>
<%= f.text_field :item %>
<%= f.number_field :price, :class => 'text_field', :step => 'any' %>
<%= f.check_box :bought, label: "Bought?", :class => "bought" %>
<%= f.submit class: "submit", class: "btn btn-default", value: "Submit" %>
<% end %>

</div>

app/views/wishlists/edit.html.erb
<%= render "form" %>

app/views/wishlists/index.html.erb
<h1><%= @title %></h1>
<table class="table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Bought?</th>
    </tr>
  </thead>
  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.item %></td>
        <td>
          <% if wishlist.price != nil %>
            <%= number_to_currency(wishlist.price) %>
          <% else %>
            -
          <% end %>
          </td>
        <td>
          <% if wishlist.bought == false %>
            No
          <% else %>
            Yes
          <% end %>
        </td>
        <td>
          <%= button_to "Edit Item", { action: "edit", id: wishlist.id }, method: :get, class: "btn btn-default" %>
        </td>
        <td>
          <%= button_to "Delete Item", { action: "destroy", id: wishlist.id }, method: :delete, data: { confirm: "Last chance...you sure?" }, class: "btn btn-default" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to "Add New Item", new_giftee_wishlist_path, method: :get, class: "btn btn-default" %>

app/views/wishlists/new.html.erb
<%= render "form" %>